### ISSUE TITLE
setContent.file

### ISSUE THREAD

**Issue by Dumi-k** [joseconstela/webparsy#30]
webparsy\helpers\steps.js \:82

`fs.readFileSync` return **Buffer**
------------------------------------------
`page.setContent` need a **String**
------------------------------------------
edit

const html = await fs.readFileSync(parameters.file)**.toString()**

**Comment by joseconstela** [comment]
Thanks a lot for your findings @Dumi-k! This has been solved in the latest release. 

How are you finding Webparsy for your needs?

@all-contributors please add @Dumi-k for bug
