### ISSUE TITLE
Add scroll support

### ISSUE THREAD

**Issue by KilianCM** [joseconstela/webparsy#32]
It could be great if we can scroll to bottom of the window. 
Some websites use lazy loading for content and all the data is not loading until you are not at the bottom of the page.

Ideas of options: 
- to bottom/top
- to selector
- to xpath
- to specific y position

**Comment by joseconstela** [comment]
Very good idea indeed 🤔. How do you feel about creating a PullRequest yourself? I've seen you have JavaScript skill. Let me know if you need any help or support implementing it!

@all-contributors please add @KilianCM for ideas

**Comment by KilianCM** [comment]
Here is the PR 👉 https://github.com/joseconstela/webparsy/pull/34

**Comment by joseconstela** [comment]
That was quick!

I also added "scrollToEnd" for infinite scrolling pages.

**Comment by joseconstela** [comment]
@all-contributors please add @KilianCM for code
